name: Deploy Frontend
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t brtkozak/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true brtkozak/docker-react npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: bartosz-app
          environment_name: Bartoszapp-env
          existing_bucket_name: elasticbeanstalk-eu-west-1-979213071888
          region: eu-west-1
          version_label: "Sample Application"
          deployment_package: deploy.zip